server:
  port: 8080

spring:
  profiles:
    active: local #change if using other database
  datasource:
    generate-unique-name: false
    jdbcUrl: jdbc:mysql://localhost:3306/test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    database-platform: com.mysql.cj.jdbc.Driver
    liquibase:
      change-log: classpath:/db/change-log/master-change-log.yaml
